stages:
  - stage: Build
    jobs:
      - job: Linux
        pool:
          vmImage: ubuntu-latest
        container:
          image: trojangfw/centos-build:latest
        steps:
          - script: |
              set -euo pipefail
              cmake -DBoost_USE_STATIC_LIBS=ON .
              make
              strip -s overplus
          - publish: $(System.DefaultWorkingDirectory)/overplus
            artifact: LinuxBinary
      - job: Windows
        pool:
          vmImage: windows-latest
        variables:
          - name: VCPKG_BINARY_SOURCES
            value: 'clear;nuget,https://pkgs.dev.azure.com/overplusProxy/overplus/_packaging/vcpkg_cache/nuget/v3/index.json,readwrite'
        steps:
          # Remember to add this task to allow vcpkg to upload archives via NuGet
          - task: NuGetAuthenticate@0
            displayName: 'NuGet Authenticate'
          - script: git clone https://github.com/microsoft/vcpkg
            displayName: Checkout vcpkg
          - script: .\vcpkg\bootstrap-vcpkg.bat
            displayName: Bootstrap vcpkg
          - bash: |
              set -euo pipefail
              cmake  -A x64 -B . -S .  -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake 
              cmake --build . --config Release
          - publish: $(System.DefaultWorkingDirectory)/Release
            artifact: WindowsBinary
  - stage: Package
    jobs:
      - job: Linux
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            artifact: LinuxBinary
          - script: |
              set -euo pipefail
              BINARY="$PIPELINE_WORKSPACE/LinuxBinary/overplus"
              chmod +x "$BINARY"
              mkdir overplus
              cp "$BINARY" overplus/overplus
              cp -r ConfigTemplate overplus
              tar cf overplus-linux-amd64.tar overplus
              xz overplus-linux-amd64.tar
            env:
              PIPELINE_WORKSPACE: $(Pipeline.Workspace)
          - publish: $(System.DefaultWorkingDirectory)/overplus-linux-amd64.tar.xz
            artifact: LinuxRelease
      - job: Windows
        pool:
          vmImage: windows-latest
        steps:
          - download: current
            artifact: WindowsBinary
          - bash: |
              set -euo pipefail
              BINARY="$PIPELINE_WORKSPACE/WindowsBinary/"
              mkdir overplus
              cp -r "$BINARY" overplus/
              cp  ConfigTemplate/client.json overplus/.
              7z a -mx=9 overplus-win.zip overplus
            env:
              PIPELINE_WORKSPACE: $(Pipeline.Workspace)
          - publish: $(System.DefaultWorkingDirectory)/overplus-win.zip
            artifact: WindowsRelease
